In [66]:
from scipy.integrate import quad_vec
import numpy as np
from scipy.special import gamma, eval_hermite

In [8]:
dim=3
def f(D,N): #f(D,N) has dimension D along axis 1
    if D==1:
        return np.array([[N]],dtype=int)
    ar=np.ones((1,D),dtype=int)
    for k in np.arange(1,N):
        prev=f(D-1,N-k) #M,D-1
        size = np.shape(prev)[0]
        ks = k*np.ones((size,1),dtype=int) #M,1
        ark = np.concatenate([ks,prev],axis=1) #M,D
        #print(np.shape(ark))
        #print(np.shape(ar))
        ar = np.concatenate([ar,ark],axis=0)
    return ar[1:,:]

max_deg = 11
ind_list=np.ones((1,dim),dtype=int)
for m in range(1,max_deg):
    ind_list=np.concatenate([ind_list,f(dim,m)])

In [51]:
## including gamma factors in the RBF tables: 
bmat = np.loadtxt("../LCDM/RBFtables/ext/bmat_wts_LCDMext.dat",unpack=True)
print(np.shape(bmat))

dim=3
eps=0.1
alpha=1.8 ##important!! Inverse global length scale associated with the problem, take alpha = 2 or 3?
beta=(1+(2*eps/alpha)**2)**(1/4)
deltasq=(alpha**2/2)*(beta**2-1)

max_deg=11 ## maximum sum plus one 
ind_list=np.ones((1,dim),dtype=int)
for m in range(1,max_deg):
    ind_list=np.concatenate([ind_list,f(dim,m)])
    
ind_list=ind_list[1:]

n_eig=np.shape(ind_list)[0] #total number of eigenfunctions used in D dims
#print(n_eig)
gamma_fac = np.sqrt((beta**dim)/(2**(np.sum(ind_list,axis=1)-dim)*np.prod(gamma(ind_list),axis=1)))
np.shape(gamma_fac)

(120, 16)


(10,)

In [69]:
## including gamma factors in the RBF tables: 
bmat = np.loadtxt("../GEN/RBFtables/def/bmat_wts_GENdef.dat",unpack=True)
print(np.shape(bmat))

dim=9
## set up the interpolator as usual 
def f(D,N): #f(D,N) has dimension D along axis 1
    if D==1:
        return np.array([[N]],dtype=int)
    ar=np.ones((1,D),dtype=int)
    for k in np.arange(1,N):
        prev=f(D-1,N-k) #M,D-1
        size = np.shape(prev)[0]
        ks = k*np.ones((size,1),dtype=int) #M,1
        ark = np.concatenate([ks,prev],axis=1) #M,D
        #print(np.shape(ark))
        #print(np.shape(ar))
        ar = np.concatenate([ar,ark],axis=0)
    return ar[1:,:]

eps=0.1
alpha=2.5 ##important!! Inverse global length scale associated with the problem, take alpha = 2 or 3?
beta=(1+(2*eps/alpha)**2)**(1/4)
deltasq=(alpha**2/2)*(beta**2-1)

max_deg=16
ind_list=np.ones((1,dim),dtype=int)
for m in range(1,max_deg):
    ind_list=np.concatenate([ind_list,f(dim,m)])
    
ind_list=ind_list[1:]
ind_array_m = ind_list - 1 

unit_cube_points = np.ones((20,dim))

n_eig=np.shape(ind_list)[0] #total number of eigenfunctions used in D dims
#print(n_eig)
gamma_fac = np.sqrt((beta**dim)/(2**(np.sum(ind_list,axis=1)-dim)*np.prod(gamma(ind_list),axis=1)))
np.shape(gamma_fac)
md = max_deg - dim

exp_fac = np.exp(-deltasq * np.linalg.norm(unit_cube_points, axis=1) ** 2)
herm = eval_hermite(np.arange(md)[:, None], alpha * beta * unit_cube_points[:, None, :])
ev = np.prod(herm[:, ind_array_m, np.arange(dim)], axis=2)
psi = (exp_fac[:, None] * ev).T  

print(np.shape(psi))


(5005, 17)
(5005, 20)


In [61]:
bmat = np.loadtxt("../GEN/RBFtables/ext/bmat_d_GENext.dat",unpack=True)
print(np.shape(bmat))
dim_g = 6

eps_g=0.1
alpha_g=1.8 ##important!! Inverse global length scale associated with the problem, take alpha = 2 or 3?
beta_g=(1+(2*eps_g/alpha_g)**2)**(1/4)
deltasq_g=(alpha_g**2/2)*(beta_g**2-1)

max_deg_g=15
ind_list_g=np.ones((1,dim_g),dtype=int)
for m in range(1,max_deg_g):
    ind_list_g=np.concatenate([ind_list_g,f(dim_g,m)])


    
ind_list_g=ind_list_g[1:]
gamma_fac_g = np.sqrt((beta_g**dim_g)/(2**(np.sum(ind_list_g,axis=1)-dim_g)*np.prod(gamma(ind_list_g),axis=1)))
np.shape(gamma_fac_g)


(3003,)


(3003,)

In [100]:
np.shape(np.loadtxt("eh_spec.dat",unpack=True))

(600, 2)

In [99]:
np.ceil(12.5,dtype=int)

TypeError: No loop matching the specified signature and casting was found for ufunc ceil

In [64]:
bmat = np.loadtxt("../LCDM/Stables/",unpack=True)
print(np.shape(bmat))

(5005, 17)


In [78]:
bmat = np.loadtxt("../GEN/RBFtables/def/bmat_wts_GENdef.dat",unpack=True)
np.shape(bmat)

(5005, 17)

In [82]:
bmat[:,-1]

array([ 1.84596362e+00, -1.24871777e-02, -1.55048364e-02, ...,
       -8.79033156e-08,  1.66496958e-07, -3.13125792e-08])

In [80]:
bmat2 = np.roll(bmat,1,axis=1)

In [83]:
bmat2[:,0]

array([ 1.84596362e+00, -1.24871777e-02, -1.55048364e-02, ...,
       -8.79033156e-08,  1.66496958e-07, -3.13125792e-08])

In [84]:
np.savetxt("../GEN/RBFtables/def/bmat_wts_GENdef.dat",bmat2)

In [91]:
bmat = np.loadtxt("../GEN/RBFtables/def/bmat_wts_GENdef.dat",unpack=True)
np.shape(bmat)

(17, 5005)

In [96]:
bmat[1]/gamma_fac

array([ 2.52545576e+01,  1.64019384e-01, -5.92943554e-03, ...,
       -1.06336470e-04, -1.52687220e-04,  3.05013880e-03])

In [93]:
np.shape(gamma_fac)

(5005,)

In [97]:
bmat[1]

array([ 2.54364630e+01,  1.16814602e-01, -4.22294389e-03, ...,
       -1.22213333e-06, -1.75484610e-06,  1.43113408e-05])

In [101]:
def func(a:int):
    return a+1

In [103]:
eh = np.loadtxt("../Utils/eh_spec.dat",unpack=True)

In [121]:
eh[277]

array([8.20034079e-03, 2.04618015e+04])